[[redirects]]
  from = "/faq"
  to = "https://bloom.host/faqs"

[[redirects]]
  from = "/plugins/papi"
  to = "/plugins/placeholderapi"

############# 
# These redirects were added when the multi-platform category for plugins and mods was added.
# Some existing plugin/mod pages were moved (and in some cases, merged) from the platform-specific folder into the mult-platform folder.
# These redirect rules are to allow old links to continue to work as they get redirected to the new locations.


[[redirects]] # LuckPerms for Fabric page
  from = "/f_luckperms"
  to = "/multiplatform/luckperms"

[[redirects]] # Chunky for Fabric page
  from = "/f_chunky"
  to = "/multiplatform/chunky"

[[redirects]] # Chunky for Bukkit/Spigot/Paper page
  from = "/plugins/chunky"
  to = "/multiplatform/chunky"

[[redirects]] # LuckPerms for Bukkit/Spigot/Paper page
  from = "/plugins/luckperms"
  to = "/multiplatform/luckperms"

[[redirects]] # Simple Voice Chat page
  from = "/installing-simple-voice-chat"
  to = "/multiplatform/simple-voice-chat"

[[redirects]] # LiteBans page
  from = "/plugins/litebans"
  to = "/multiplatform/litebans"

[[redirects]] # PLayer ANalytics page
  from = "/plan"
  to = "/multiplatform/plan"

[[redirects]] # Dynmap page
  from = "/plugins/dynmap"
  to = "/multiplatform/dynmap"

[[redirects]] # AdvancedBan page
  from = "/plugins/advancedban"
  to = "/multiplatform/advancedban"

[[redirects]] # WorldEdit page
  from = "/plugins/worldedit"
  to = "/multiplatform/worldedit"
#############
